import asyncio
from playwright.async_api import async_playwright
S="/home/claude/busapp/test/shots/"
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        for scheme in ["light","dark"]:
            ctx=await b.new_context(viewport={"width":390,"height":844},device_scale_factor=2,is_mobile=True,has_touch=True,color_scheme=scheme,locale="ja-JP")
            pg=await ctx.new_page()
            errs=[]; pg.on("pageerror",lambda e: errs.append(str(e))); pg.on("console",lambda m: m.type=="error" and errs.append(m.text))
            await pg.goto("http://localhost:8765/#/"); await pg.wait_for_timeout(500)
            await pg.screenshot(path=S+f"{scheme}-1-home-empty.png")
            await pg.click("#btnSearch"); await pg.wait_for_timeout(500)
            await pg.screenshot(path=S+f"{scheme}-2-search.png")
            await pg.click("text=サンプル交通"); await pg.wait_for_timeout(500)
            await pg.screenshot(path=S+f"{scheme}-3-stops.png")
            await pg.click("text=市役所前"); await pg.wait_for_timeout(800)
            await pg.click("#star"); await pg.wait_for_timeout(300)
            await pg.screenshot(path=S+f"{scheme}-4-stop.png")
            await pg.click("#backBtn"); await pg.wait_for_timeout(300)
            await pg.click("text=青葉台"); await pg.wait_for_timeout(600); await pg.click("#star")
            await pg.click("#backBtn"); await pg.click("text=中央駅"); await pg.wait_for_timeout(600); await pg.click("#star")
            await pg.click("#backBtn"); await pg.wait_for_timeout(200); await pg.click("#backBtn"); await pg.wait_for_timeout(200); await pg.click("#backBtn"); await pg.wait_for_timeout(1000)
            print(scheme, "url", pg.url)
            await pg.screenshot(path=S+f"{scheme}-5-home.png")
            await pg.click("#btnEdit"); await pg.wait_for_timeout(300)
            await pg.screenshot(path=S+f"{scheme}-6-edit.png")
            # drag 1st row's handle down 2 rows
            rows=await pg.query_selector_all("#favList .row")
            bb=await rows[0].bounding_box()
            await pg.mouse.move(bb["x"]+bb["width"]-20,bb["y"]+bb["height"]/2); await pg.mouse.down()
            for i in range(10): await pg.mouse.move(bb["x"]+bb["width"]-20,bb["y"]+bb["height"]/2+bb["height"]*2.1*(i+1)/10)
            await pg.mouse.up(); await pg.wait_for_timeout(300)
            print(scheme,"after drag", await pg.eval_on_selector_all("#favList .t","e=>e.map(x=>x.textContent)"))
            await pg.click("[data-del='0']"); await pg.wait_for_timeout(400)
            print(scheme,"after delete", await pg.eval_on_selector_all("#favList .t","e=>e.map(x=>x.textContent)"))
            await pg.screenshot(path=S+f"{scheme}-7-after.png")
            await pg.click("#btnEdit"); await pg.wait_for_timeout(800)
            await pg.reload(); await pg.wait_for_timeout(800)
            print(scheme,"persisted", await pg.eval_on_selector_all("#favList .t","e=>e.map(x=>x.textContent)"))
            print(scheme,"errors",errs)
            await ctx.close()
        await b.close()
asyncio.run(main())
